/**
 * Our own icon rules — the part flow's mapping has no answer for.
 *
 * Extracted once from the tables this project maintained before the flow pack
 * arrived, then kept by hand. Two kinds live here and both are deliberate:
 *
 *  • suffix patterns. We match `.test.ts` and `.stories.tsx` by their tail,
 *    where flow enumerates every whole filename it knows. Ours generalises to
 *    a file it has never seen; theirs does not.
 *  • colour folders. A folder literally named `blue` or `green` takes that
 *    colour. flow has no such notion, and it is a small thing people like.
 *
 * These win over flow's map, so anything added here shadows the pack. Add
 * sparingly, and prefer fixing the pack's own name when there is one.
 */

/** Extensions and whole filenames flow does not map. */
export const OURS_EXT: Record<string, string> = {
  ".code-workspace": "vscode",
  ".d.luau": "luau-def",
  ".d.ts": "typescript_def",
  ".dockerignore": "docker_ignore",
  ".luarc.json": "lua-config",
  ".mocharc": "mocha",
  ".spec.js": "test_ts",
  ".spec.ts": "test_ts",
  ".stories.js": "storybook",
  ".stories.ts": "storybook",
  ".stories.tsx": "storybook",
  ".test.js": "test_ts",
  ".test.ts": "test_ts",
  ".test.tsx": "test_ts",
  ".vimrc": "vim",
  "astro.config": "astro-config",
  "babel.config": "babel",
  "cypress.config": "cypress",
  "default.project.json": "roblox-config",
  "drizzle.config": "drizzle-orm",
  "edn": "clojure",
  "el": "lisp",
  "eml": "email",
  "eslint": "eslint",
  "gitattributes": "git",
  "gitignore": "git",
  "handlebars": "handlebars",
  "hrl": "erlang",
  "import": "godot_assets",
  "jest.config": "jest",
  "mat": "matlab",
  "msg": "email",
  "next.config": "next",
  "nims": "nim",
  "node": "nodejs",
  "npm-shrinkwrap.json": "npm_lock",
  "nuxt.config": "nuxt",
  "postcss.config": "postcss",
  "pp": "puppet",
  "prettier": "settings",
  "prettier.config": "prettier",
  "scpt": "applescript",
  "tailwind.config": "tailwindcss",
  "text": "document",
  "vite.config": "vite",
  "vsh": "vlang",
  "vue.config": "vue_config",
  "webpack.config": "webpack",
};

/** Folder names flow does not map. */
export const OURS_FOLDERS: Record<string, string> = {
  "aurelia": "folder_aurelia",
  "azure_pipelines": "folder_azure_pipelines",
  "blue": "folder_blue",
  "bower": "folder_bower",
  "brown": "folder_brown",
  "builder": "folder_builder",
  "camera": "folder_camera",
  "chevron": "folder_chevron",
  "ci": "folder_script",
  "cline": "folder_cline",
  "cloud_functions": "folder_cloud_functions",
  "cloudflare_worker": "folder_cloudflare_worker",
  "cloudflare-worker": "folder_cloudflare_worker",
  "effect": "folder_effects",
  "effects": "folder_effects",
  "flow": "folder_flow",
  "gh_workflows": "folder_gh_workflows",
  "gh-workflows": "folder_gh_workflows",
  "gray": "folder_gray",
  "green": "folder_green",
  "intellij": "folder_intellij",
  "lime": "folder_lime",
  "lune": "folder_lune",
  "marketing": "folder_marketing",
  "mercurial": "folder_mercurial",
  "orange": "folder_orange",
  "ory_hydra": "folder_ory_hydra",
  "ory_keto": "folder_ory_keto",
  "ory_kratos": "folder_ory_kratos",
  "ory-hydra": "folder_ory_hydra",
  "ory-keto": "folder_ory_keto",
  "ory-kratos": "folder_ory_kratos",
  "pdm": "folder_pdm",
  "pink": "folder_pink",
  "pre_commit": "folder_pre_commit",
  "pre-commit": "folder_pre_commit",
  "purple": "folder_purple",
  "react_components": "folder_react_components",
  "red": "folder_red",
  "roblox": "folder_roblox",
  "rocket": "folder_rocket",
  "root": "folder_root",
  "sky": "folder_sky",
  "socketio": "folder_socketio",
  "src_tauri": "folder_src_tauri",
  "steering": "folder_steering",
  "teal": "folder_teal",
  "turborepo": "folder_turborepo",
  "wordpress": "folder_wordpress",
  "x_cmd": "folder_x_cmd",
  "yarn": "folder_yarn",
  "yellow": "folder_yellow",
};
