/**
 * Icon resolver — maps file extensions and folder names to charmed-icons SVGs.
 */

const EXT_MAP: Record<string, string> = {
  ts: "typescript",
  tsx: "react",
  js: "javascript",
  jsx: "react",
  mjs: "javascript",
  cjs: "javascript",
  css: "css",
  scss: "sass",
  // No `less` icon in the set; it is a CSS preprocessor, so css reads right.
  less: "css",
  html: "html",
  htm: "html",
  json: "json",
  jsonc: "json",
  md: "markdown",
  mdx: "markdown",
  svg: "svg",
  png: "image",
  jpg: "image",
  jpeg: "image",
  gif: "image",
  webp: "image",
  // No `favicon` icon; a .ico IS an image, which is the honest fallback.
  ico: "image",
  py: "python",
  rs: "rust",
  go: "go",
  java: "java",
  kt: "kotlin",
  scala: "scala",
  cs: "csharp",
  php: "php",
  rb: "ruby",
  swift: "swift",
  dart: "dart",
  c: "c",
  h: "c-header",
  cpp: "cpp",
  hpp: "cpp-header",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  ps1: "powershell",
  bat: "bash",
  cmd: "bash",
  sql: "database",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  csv: "csv",
  env: "settings",
  gitignore: "git",
  gitattributes: "git",
  dockerfile: "docker",
  dockerignore: "docker",
  eslint: "eslint",
  prettier: "settings",
  lock: "lock",
  "package.json": "nodejs",
  "tsconfig.json": "tsconfig",
  "vite.config": "vite",
  readme: "readme",
  license: "license",
  changelog: "changelog",
  // The set HAS a makefile icon; this pointed at the shell one, which is the
  // same class of mistake as the mappings that pointed at names the set never
  // had. Same symptom too: a file drawn as something it is not.
  makefile: "makefile",
};

/**
 * The rest of the set.
 *
 * Reported: "в дереве не все типы показываются иконки, они рисуются обычным
 * файлом". Measured — the set ships 249 icons and only 102 names were reachable,
 * so 73 FILE icons were sitting on disk that nothing could ever ask for. `.pdf`,
 * `.zip`, `.txt`, `.lua`, `.vue`, `.tex`, fonts, audio, video and a Makefile all
 * drew the generic page.
 *
 * The earlier fix was the opposite mistake — mappings pointing at names the set
 * does not have — and the check only looked in that direction. It looks both ways
 * now.
 *
 * Five icons are still unreachable on purpose, because nothing in a FILENAME can
 * honestly select them: `css3` (an alternative to `css`), `test-teal` and
 * `test-yellow` (colour variants with no signal to pick between them),
 * `roblox-lock`, `event`, and `workflow` — which wants `.github/workflows/`, a PATH, and
 * this resolver is given a name. The probe pins that list, so the next icon added
 * to the set does not quietly join it.
 */
const MORE_EXT: Record<string, string> = {
  // Documents and plain data
  pdf: "pdf",
  txt: "document",
  text: "document",
  rtf: "document",
  log: "document",
  todo: "todo",
  tex: "tex",
  bib: "tex",
  // Archives — one icon for the family
  zip: "zip",
  "7z": "zip",
  rar: "zip",
  tar: "zip",
  gz: "zip",
  tgz: "zip",
  xz: "zip",
  bz2: "zip",
  zst: "zip",
  // Media
  mp3: "audio",
  wav: "audio",
  flac: "audio",
  ogg: "audio",
  m4a: "audio",
  aac: "audio",
  mp4: "video",
  mov: "video",
  mkv: "video",
  avi: "video",
  webm: "video",
  wmv: "video",
  woff: "font",
  woff2: "font",
  ttf: "font",
  otf: "font",
  eot: "font",
  // Binaries and keys
  exe: "binary",
  dll: "binary",
  so: "binary",
  dylib: "binary",
  bin: "binary",
  wasm: "webassembly",
  pem: "key",
  crt: "key",
  cer: "key",
  pub: "key",
  // Languages the set has and the map did not
  lua: "lua",
  luau: "luau",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  jl: "julia",
  nim: "nim",
  nims: "nim",
  nix: "nix",
  odin: "odin",
  gleam: "gleam",
  zig: "zig",
  zon: "zig",
  pl: "perl",
  pm: "perl",
  f: "fortran",
  f90: "fortran",
  f95: "fortran",
  f77: "fortran-fixed",
  asm: "assembly",
  s: "assembly",
  hcl: "hcl",
  tf: "terraform",
  tfvars: "terraform",
  pcss: "pcss",
  // Named files. These are matched whole, or by suffix — see iconName.
  "go.mod": "go-mod",
  "go.sum": "go-mod",
  "cargo.toml": "cargo",
  "justfile": "just",
  "jsconfig.json": "jsconfig",
  "package-lock.json": "npm_lock",
  "yarn.lock": "yarn_lock",
  ".yarnrc": "yarn",
  ".yarnrc.yml": "yarn",
  ".npmrc": "npm",
  "bun.lockb": "bun_lock",
  "bunfig.toml": "bun",
  "wally.toml": "wally",
  "wally.lock": "wally-lock",
  "code_of_conduct.md": "code-of-conduct",
  codeowners: "codeowners",
  "security.md": "security",
  ".luarc.json": "lua-config",
  // Config files, by the part of the name that identifies them
  "next.config": "next",
  "nuxt.config": "nuxt",
  "astro.config": "astro-config",
  "tailwind.config": "tailwindcss",
  "drizzle.config": "drizzle-orm",
  ".code-workspace": "vscode",
  sln: "visual-studio",
  ".d.ts": "typescript_def",
  ".d.luau": "luau-def",
  ".stories.ts": "storybook",
  ".stories.tsx": "storybook",
  ".stories.js": "storybook",
  ".nvmrc": "nodejs",
  node: "nodejs",
  // Where the set draws a finer distinction than the map did
  mdx: "mdx",
  tsx: "react_ts",
  "package.json": "nodejs",
  "npm-shrinkwrap.json": "npm_lock",
  ".luaurc": "luau-config",
  "default.project.json": "roblox-config",
  ".test.ts": "test_ts",
  ".test.tsx": "test_ts",
  ".test.js": "test_ts",
  ".spec.ts": "test_ts",
  ".spec.js": "test_ts",
  // Godot and Roblox, which the set covers
  gd: "godot",
  tscn: "godot",
  tres: "godot",
  import: "godot_assets",
  rbxl: "roblox",
  rbxlx: "roblox",
  rbxm: "roblox-model",
  rbxmx: "roblox-model",
};

/**
 * What the flow icon set adds.
 *
 * The set ships 230 file icons and 670 folder icons against the previous 116 and
 * 130, so most of this is types that used to draw the generic page: Elixir,
 * Erlang, F#, Haskell, OCaml, Solidity, Verilog, Jupyter, GraphQL, Gradle, a
 * docker-compose, a .gitignore drawn as an ignore file rather than as git.
 *
 * Added rather than merged into the tables above so it is obvious what came from
 * where, and it is applied last, so where both name the same extension this one
 * wins — that is the point of taking the newer set.
 */
const FLOW_EXT: Record<string, string> = {
  // Archives, each its own now that the set draws them
  "7z": "7zip",
  rar: "rar",
  tar: "tar",
  // Languages the flow set covers and we did not
  applescript: "applescript",
  scpt: "applescript",
  clj: "clojure",
  cljs: "clojurescript",
  edn: "clojure",
  cmake: "cmake",
  cob: "cobol",
  cbl: "cobol",
  coffee: "coffee",
  cu: "cuda",
  cuh: "cuda",
  ex: "elixir",
  exs: "elixir",
  elm: "elm",
  erl: "erlang",
  hrl: "erlang",
  fs: "fsharp",
  fsx: "fsharp",
  fsproj: "fsharp",
  groovy: "groovy",
  gradle: "gradle",
  gradlew: "gradlew",
  haml: "haml",
  hbs: "handlebars",
  handlebars: "handlebars",
  hs: "haskell",
  hx: "haxe",
  lean: "lean",
  liquid: "liquid",
  lisp: "lisp",
  el: "lisp",
  scm: "scheme",
  ss: "scheme",
  ml: "ocaml",
  mli: "ocaml",
  m: "objective_c",
  mm: "objective_c",
  purs: "purescript",
  re: "reason",
  res: "rescript",
  rkt: "racket",
  qs: "qsharp",
  r: "r",
  rmd: "r",
  sol: "solidity",
  templ: "templ",
  typ: "typst",
  vala: "vala",
  v: "verilog",
  sv: "verilog",
  vsh: "vlang",
  pde: "processing",
  proto: "proto",
  pp: "puppet",
  pug: "pug",
  jade: "pug",
  jinja: "jinja",
  j2: "jinja",
  njk: "nunjucks",
  twig: "twig",
  slim: "slim",
  slint: "slint",
  tpl: "smarty",
  ejs: "ejs",
  razor: "razor",
  cshtml: "razor",
  graphql: "graphql",
  gql: "graphql",
  robot: "robot",
  yang: "yang",
  d: "d",
  hex: "hex",
  // Styles the set separates
  sass: "sass",
  scss: "sass",
  less: "less",
  styl: "stylus",
  // Notebooks, docs and data
  ipynb: "jupyter",
  nb: "mathematica",
  wl: "mathematica",
  mat: "matlab",
  doc: "word",
  docx: "word",
  ppt: "powerpoint",
  pptx: "powerpoint",
  eml: "email",
  msg: "email",
  diff: "diff",
  patch: "diff",
  http: "http",
  rest: "http",
  // Fonts and pictures the set draws separately
  otf: "otf",
  ttf: "ttf",
  webp: "webp",
  fig: "figma",
  sketch: "sketch",
  // Build, lint and CI files, matched whole
  "docker-compose.yml": "docker_compose",
  "docker-compose.yaml": "docker_compose",
  "compose.yml": "docker_compose",
  "compose.yaml": "docker_compose",
  ".dockerignore": "docker_ignore",
  ".gitignore": "git_ignore",
  ".eslintignore": "eslint_ignore",
  ".prettierignore": "prettier_ignore",
  ".stylelintignore": "stylelint_ignore",
  ".stylelintrc": "stylelint",
  ".editorconfig": "editorconfig",
  ".pre-commit-config.yaml": "pre_commit",
  ".gitlab-ci.yml": "gitlab",
  "bitbucket-pipelines.yml": "bitbucket",
  "azure-pipelines.yml": "azure_pipelines",
  "nginx.conf": "nginx",
  "cmakelists.txt": "cmake",
  "deno.json": "deno",
  "deno.lock": "deno_lock",
  "pnpm-lock.yaml": "pnpm_lock",
  "pnpm-workspace.yaml": "pnpm",
  "cargo.lock": "cargo_lock",
  "xmake.lua": "xmake",
  "chart.yaml": "helm",
  "openapi.yaml": "openapi",
  "swagger.yaml": "openapi",
  "babel.config": "babel",
  ".babelrc": "babel",
  "jest.config": "jest",
  "webpack.config": "webpack",
  "postcss.config": "postcss",
  "vue.config": "vue_config",
  "cypress.config": "cypress",
  ".mocharc": "mocha",
  ".prettierrc": "prettier",
  "prettier.config": "prettier",
  // Triggers the flow set earns
  ahk: "autohotkey",
  bal: "ballerina",
  cabal: "cabal",
  cake: "cake",
  "claude.md": "claude",
  ".cursorrules": "cursor",
  iso: "disc",
  doxyfile: "doxygen",
  ".drone.yml": "drone",
  "faq.md": "faq",
  ".gitpod.yml": "gitpod",
  "phpstan.neon": "phpstan",
  "phpunit.xml": "phpunit",
  unity: "unity",
  vim: "vim",
  vimrc: "vim",
  ".vimrc": "vim",
  obj: "3d",
  "3ds": "3d",
  blend: "3d",
  fbx: "3d",
  gltf: "3d",
  glb: "3d",
  "androidmanifest.xml": "android",
  "angular.json": "angular",
  "cargo.toml": "cargo",
  // Compiled and packaged output
  jar: "jar",
  class: "javaclass",
  pyc: "python_compiled",
  "css.map": "css_map",
  "js.map": "javascript_map",
};

/**
 * Folders, by their own name.
 *
 * Mechanical and honest: the set draws `folder_django`, so a directory called
 * `django` gets it. Generated from the set rather than typed, with no invented
 * plurals — `activitys` is not a directory anyone has.
 */
const FLOW_FOLDERS: Record<string, string> = {
  activity: "folder_activity",
  android: "folder_android",
  angular: "folder_angular",
  ansible: "folder_ansible",
  antigravity: "folder_antigravity",
  api: "folder_api",
  apollo: "folder_apollo",
  appwrite: "folder_appwrite",
  archive: "folder_archive",
  assembly: "folder_assembly",
  astro: "folder_astro",
  atom: "folder_atom",
  attachment: "folder_attachment",
  attribute: "folder_attribute",
  aurelia: "folder_aurelia",
  aws: "folder_aws",
  azure_pipelines: "folder_azure_pipelines",
  "azure-pipelines": "folder_azure_pipelines",
  backup: "folder_backup",
  base: "folder_base",
  blender: "folder_blender",
  blog: "folder_blog",
  blue: "folder_blue",
  bower: "folder_bower",
  brown: "folder_brown",
  bruno: "folder_bruno",
  builder: "folder_builder",
  buildkite: "folder_buildkite",
  cargo: "folder_cargo",
  cart: "folder_cart",
  chart: "folder_chart",
  chevron: "folder_chevron",
  circleci: "folder_circleci",
  class: "folder_class",
  claude: "folder_claude",
  cline: "folder_cline",
  cloud: "folder_cloud",
  cloud_functions: "folder_cloud_functions",
  "cloud-functions": "folder_cloud_functions",
  cloudflare: "folder_cloudflare",
  cloudflare_worker: "folder_cloudflare_worker",
  "cloudflare-worker": "folder_cloudflare_worker",
  cmake: "folder_cmake",
  codegraph: "folder_codegraph",
  codesandbox: "folder_codesandbox",
  codex: "folder_codex",
  command: "folder_command",
  composables: "folder_composables",
  conductor: "folder_conductor",
  console: "folder_console",
  container: "folder_container",
  contract: "folder_contract",
  controller: "folder_controller",
  convex: "folder_convex",
  core: "folder_core",
  crush: "folder_crush",
  cue: "folder_cue",
  cursor: "folder_cursor",
  curve: "folder_curve",
  custom: "folder_custom",
  cypress: "folder_cypress",
  dart: "folder_dart",
  debug: "folder_debug",
  decorators: "folder_decorators",
  desktop: "folder_desktop",
  devenv: "folder_devenv",
  diff: "folder_diff",
  digitalocean: "folder_digitalocean",
  directive: "folder_directive",
  docker: "folder_docker",
  domain: "folder_domain",
  download: "folder_download",
  drizzle: "folder_drizzle",
  dump: "folder_dump",
  element: "folder_element",
  enum: "folder_enum",
  eslint: "folder_eslint",
  examples: "folder_examples",
  expo: "folder_expo",
  export: "folder_export",
  fastlane: "folder_fastlane",
  favicon: "folder_favicon",
  features: "folder_features",
  files: "folder_files",
  filter: "folder_filter",
  firebase: "folder_firebase",
  firestore: "folder_firestore",
  fish: "folder_fish",
  flow: "folder_flow",
  flutter: "folder_flutter",
  forgejo: "folder_forgejo",
  form: "folder_form",
  gamemaker: "folder_gamemaker",
  gemini_ai: "folder_gemini_ai",
  "gemini-ai": "folder_gemini_ai",
  generator: "folder_generator",
  gh_workflows: "folder_gh_workflows",
  "gh-workflows": "folder_gh_workflows",
  git: "folder_git",
  gitbook: "folder_gitbook",
  gitea: "folder_gitea",
  gitlab: "folder_gitlab",
  global: "folder_global",
  go: "folder_go",
  godot: "folder_godot",
  gradle: "folder_gradle",
  graphql: "folder_graphql",
  gray: "folder_gray",
  green: "folder_green",
  grype: "folder_grype",
  guard: "folder_guard",
  gulp: "folder_gulp",
  helper: "folder_helper",
  history: "folder_history",
  home: "folder_home",
  husky: "folder_husky",
  i18n: "folder_i18n",
  idea: "folder_idea",
  import: "folder_import",
  include: "folder_include",
  infrastructure: "folder_infrastructure",
  instruction: "folder_instruction",
  intellij: "folder_intellij",
  interceptor: "folder_interceptor",
  interface: "folder_interface",
  internal: "folder_internal",
  ios: "folder_ios",
  java: "folder_java",
  javascript: "folder_javascript",
  jinja: "folder_jinja",
  job: "folder_job",
  json: "folder_json",
  jupyter: "folder_jupyter",
  karma: "folder_karma",
  keys: "folder_keys",
  kiro: "folder_kiro",
  kotlin: "folder_kotlin",
  kubernetes: "folder_kubernetes",
  lefthook: "folder_lefthook",
  less: "folder_less",
  lime: "folder_lime",
  link: "folder_link",
  linux: "folder_linux",
  log: "folder_log",
  lottie: "folder_lottie",
  lua: "folder_lua",
  luau: "folder_luau",
  lune: "folder_lune",
  macos: "folder_macos",
  maestro: "folder_maestro",
  mail: "folder_mail",
  markdown: "folder_markdown",
  marketing: "folder_marketing",
  mercurial: "folder_mercurial",
  messages: "folder_messages",
  migrations: "folder_migrations",
  mjml: "folder_mjml",
  mobile: "folder_mobile",
  mock: "folder_mock",
  modal: "folder_modal",
  mojo: "folder_mojo",
  molecule: "folder_molecule",
  moon: "folder_moon",
  netlify: "folder_netlify",
  next: "folder_next",
  nginx: "folder_nginx",
  note: "folder_note",
  notification: "folder_notification",
  nuget: "folder_nuget",
  nuxt: "folder_nuxt",
  nx: "folder_nx",
  object: "folder_object",
  obsidian: "folder_obsidian",
  opencode: "folder_opencode",
  option: "folder_option",
  orange: "folder_orange",
  organism: "folder_organism",
  ory: "folder_ory",
  ory_hydra: "folder_ory_hydra",
  "ory-hydra": "folder_ory_hydra",
  ory_keto: "folder_ory_keto",
  "ory-keto": "folder_ory_keto",
  ory_kratos: "folder_ory_kratos",
  "ory-kratos": "folder_ory_kratos",
  other: "folder_other",
  particle: "folder_particle",
  path: "folder_path",
  pdf: "folder_pdf",
  pdm: "folder_pdm",
  php: "folder_php",
  pink: "folder_pink",
  pipe: "folder_pipe",
  plastic: "folder_plastic",
  plugin: "folder_plugin",
  policy: "folder_policy",
  postman: "folder_postman",
  powershell: "folder_powershell",
  pre_commit: "folder_pre_commit",
  "pre-commit": "folder_pre_commit",
  prefab: "folder_prefab",
  prisma: "folder_prisma",
  private: "folder_private",
  project: "folder_project",
  prompts: "folder_prompts",
  proto: "folder_proto",
  purple: "folder_purple",
  python: "folder_python",
  pytorch: "folder_pytorch",
  quasar: "folder_quasar",
  queue: "folder_queue",
  r: "folder_r",
  react_components: "folder_react_components",
  "react-components": "folder_react_components",
  red: "folder_red",
  redux: "folder_redux",
  repository: "folder_repository",
  resolver: "folder_resolver",
  resource: "folder_resource",
  review: "folder_review",
  roblox: "folder_roblox",
  robot: "folder_robot",
  rocket: "folder_rocket",
  roocode: "folder_roocode",
  room: "folder_room",
  root: "folder_root",
  ruff: "folder_ruff",
  rules: "folder_rules",
  rust: "folder_rust",
  salt: "folder_salt",
  sandbox: "folder_sandbox",
  sanity: "folder_sanity",
  sass: "folder_sass",
  scala: "folder_scala",
  schema: "folder_schema",
  scons: "folder_scons",
  sdk: "folder_sdk",
  secure: "folder_secure",
  seeders: "folder_seeders",
  sequence: "folder_sequence",
  serena: "folder_serena",
  serverless: "folder_serverless",
  shader: "folder_shader",
  shared: "folder_shared",
  simulations: "folder_simulations",
  skeleton: "folder_skeleton",
  skills: "folder_skills",
  sky: "folder_sky",
  snippet: "folder_snippet",
  socket: "folder_socket",
  socketio: "folder_socketio",
  sprite: "folder_sprite",
  src_tauri: "folder_src_tauri",
  "src-tauri": "folder_src_tauri",
  stack: "folder_stack",
  steering: "folder_steering",
  stencil: "folder_stencil",
  store: "folder_store",
  strategy: "folder_strategy",
  stylus: "folder_stylus",
  sublime: "folder_sublime",
  supabase: "folder_supabase",
  svelte: "folder_svelte",
  swift: "folder_swift",
  syntax: "folder_syntax",
  tabs: "folder_tabs",
  target: "folder_target",
  taskfile: "folder_taskfile",
  tasks: "folder_tasks",
  teal: "folder_teal",
  television: "folder_television",
  terraform: "folder_terraform",
  theme: "folder_theme",
  tile: "folder_tile",
  toc: "folder_toc",
  tools: "folder_tools",
  traefik: "folder_traefik",
  transfer: "folder_transfer",
  trash: "folder_trash",
  trigger: "folder_trigger",
  turborepo: "folder_turborepo",
  twig: "folder_twig",
  typescript: "folder_typescript",
  ui: "folder_ui",
  unity: "folder_unity",
  update: "folder_update",
  upload: "folder_upload",
  user: "folder_user",
  vercel: "folder_vercel",
  views: "folder_views",
  vm: "folder_vm",
  vue: "folder_vue",
  vuepress: "folder_vuepress",
  warning: "folder_warning",
  webp: "folder_webp",
  webpack: "folder_webpack",
  windows: "folder_windows",
  wordpress: "folder_wordpress",
  x_cmd: "folder_x_cmd",
  "x-cmd": "folder_x_cmd",
  yellow: "folder_yellow",
  zeabur: "folder_zeabur",
  zed: "folder_zed",
  zenodo: "folder_zenodo",
};

const FOLDER_MAP: Record<string, string> = {
  src: "folder_source",
  source: "folder_source",
  app: "folder_source",
  components: "folder_component",
  component: "folder_component",
  pages: "folder_page",
  page: "folder_page",
  routes: "folder_routes",
  lib: "folder_lib",
  utils: "folder_util",
  util: "folder_util",
  hooks: "folder_hooks",
  hook: "folder_hooks",
  types: "folder_types",
  type: "folder_types",
  styles: "folder_styles",
  style: "folder_styles",
  css: "folder_styles",
  public: "folder_web",
  static: "folder_web",
  assets: "folder_assets",
  images: "folder_image",
  image: "folder_image",
  img: "folder_image",
  fonts: "folder_fonts",
  font: "folder_fonts",
  tests: "folder_test",
  __tests__: "folder_test",
  test: "folder_test",
  spec: "folder_test",
  docs: "folder_docs",
  doc: "folder_docs",
  config: "folder_config",
  configs: "folder_config",
  node_modules: "folder_node",
  ".git": "folder_github",
  ".github": "folder_github",
  ".vscode": "folder_vscode",
  dist: "folder_dist",
  build: "folder_dist",
  out: "folder_dist",
  data: "folder_database",
  db: "folder_database",
  audio: "folder_audio",
  video: "folder_video",
  animation: "folder_animation",
  animations: "folder_animation",
  auth: "folder_auth",
  admin: "folder_admin",
  benchmark: "folder_benchmark",
  ci: "folder_script",
  scripts: "folder_script",
  script: "folder_script",
  bin: "folder_bin",
  commands: "folder_commands",
  server: "folder_server",
  client: "folder_client",
  packages: "folder_package",
  package: "folder_package",
  coverage: "folder_coverage",
  temp: "folder_temp",
  tmp: "folder_temp",
  templates: "folder_template",
  template: "folder_template",
  svg: "folder_svg",
  icons: "folder_svg",
  middleware: "folder_middleware",
  models: "folder_model",
  model: "folder_model",
  modules: "folder_module",
  module: "folder_module",
  providers: "folder_provider",
  provider: "folder_provider",
  services: "folder_service",
  service: "folder_service",
  events: "folder_event",
  event: "folder_event",
  functions: "folder_function",
  function: "folder_function",
  connections: "folder_connection",
  connection: "folder_connection",
  context: "folder_context",
  content: "folder_content",
  constants: "folder_constant",
  constant: "folder_constant",
  errors: "folder_error",
  error: "folder_error",
  effects: "folder_effects",
  effect: "folder_effects",
  layouts: "folder_layout",
  layout: "folder_layout",
  input: "folder_input",
  storybook: "folder_storybook",
  stories: "folder_storybook",
  changeset: "folder_changesets",
  changesets: "folder_changesets",
  yarn: "folder_yarn",
  camera: "folder_camera",
};

/**
 * Names that identify a FILE rather than a TYPE, and so may outrank an
 * extension.
 *
 * Deliberately short, and the distinction is the whole point: `readme` belongs
 * here because a README is a README whatever it is written in; `bash` does not,
 * because `bash.svg` is a picture. Getting that backwards made every icon in the
 * icon set render as its own subject.
 */
const DOC_NAMES: Record<string, string> = {
  readme: "readme",
  license: "license",
  licence: "license",
  changelog: "changelog",
  contributing: "contributing",
  authors: "authors",
  security: "security",
  code_of_conduct: "code-of-conduct",
};

/** ...and the extensions a document is actually written in. */
const DOC_EXT = new Set(["md", "markdown", "txt", "rst", "adoc", ""]);

/**
 * Config stems, matched whatever the file is written in: `vite.config.ts`,
 * `vite.config.mjs`. The dot inside the stem is what makes them unambiguous —
 * nothing is called `next.config.svg`.
 */
const CONFIG_STEMS: Record<string, string> = {
  "vite.config": "vite",
  "next.config": "next",
  "nuxt.config": "nuxt",
  "astro.config": "astro-config",
  "tailwind.config": "tailwindcss",
  "drizzle.config": "drizzle-orm",
};

/** The two tables as one lookup. Kept separate above only so the second one can
 * carry the story of why it exists. */
const ALL_EXT: Record<string, string> = { ...EXT_MAP, ...MORE_EXT, ...FLOW_EXT };

function iconName(name: string, isDir: boolean, open: boolean): string {
  if (isDir) {
    const key = name.toLowerCase();
    const mapped = FOLDER_MAP[key] ?? FLOW_FOLDERS[key];
    return mapped
      ? open
        ? mapped + "_open"
        : mapped
      : open
        ? "_folder_open"
        : "_folder";
  }

  const lower = name.toLowerCase();

  // Most specific first. The extension used to be tried before anything else,
  // so `Cargo.toml` resolved as toml, `package.json` as json and `types.d.ts`
  // as ts — and the map's own `tsconfig.json`, `vite.config`, `readme`,
  // `license` and `changelog` keys were unreachable by any filename.
  //
  // But "most specific" is not "longest match", and the first version of this
  // got that wrong in the other direction: it consulted the WHOLE map for the
  // stem, so `bash.svg` came out as bash, `c.svg` as C and `css.svg` as CSS.
  // Those are pictures. The map holds names of TYPES (bash, c, css) alongside
  // names of FILES (readme, license), and only the second kind may outrank an
  // extension — see DOC_NAMES and CONFIG_STEMS.

  // 1. The whole name: `package.json`, `go.mod`, `Makefile`, `CODEOWNERS`.
  const whole = ALL_EXT[lower];
  if (whole) return whole;

  // 2. A dotted tail: `.d.ts`, `.test.ts`, `.stories.tsx`, `.code-workspace`.
  for (const [pattern, icon] of Object.entries(ALL_EXT))
    if (pattern.startsWith(".") && lower.endsWith(pattern)) return icon;

  const dot = lower.lastIndexOf(".");
  const stem = dot > 0 ? lower.slice(0, dot) : lower;
  const ext = dot > 0 ? lower.slice(dot + 1) : "";

  // 3. A config stem, whatever it is written in: `vite.config.ts`,
  //    `next.config.mjs`. The dot inside the stem makes these unmistakable.
  const config = CONFIG_STEMS[stem];
  if (config) return config;

  // 4. A document name — but only with an extension a document is written in.
  //    This is the line that keeps `changelog.svg` a picture while
  //    `CHANGELOG.md` is a changelog.
  const doc = DOC_NAMES[stem];
  if (doc && DOC_EXT.has(ext)) return doc;

  // 5. The extension itself.
  return ALL_EXT[ext] ?? "_file";
}

export function resolveIcon(
  name: string,
  isDir: boolean,
  open: boolean,
  dark: boolean,
): string {
  const base = iconName(name, isDir, open);
  const theme = dark ? "light" : "base";
  return `./icons/${theme}/${base}.svg`;
}

/** The generic icon, for when a mapped name has no file behind it. */
export function fallbackIcon(
  isDir: boolean,
  open: boolean,
  dark: boolean,
): string {
  const theme = dark ? "light" : "base";
  const base = isDir ? (open ? "_folder_open" : "_folder") : "_file";
  return `./icons/${theme}/${base}.svg`;
}

/** Every icon name the maps can produce — for the check that they all exist. */
export function allMappedIconNames(): string[] {
  const names = new Set<string>([
    "_file",
    "_folder",
    "_folder_open",
    ...Object.values(ALL_EXT),
    ...Object.values(FLOW_FOLDERS),
    // These two were missing, so every icon reached only through a document
    // name or a config stem looked unreachable.
    ...Object.values(DOC_NAMES),
    ...Object.values(CONFIG_STEMS),
  ]);
  for (const folder of Object.values(FOLDER_MAP)) {
    names.add(folder);
    names.add(`${folder}_open`);
  }
  return [...names];
}
